version: '3'

services:
### PHP-FPM ##############################################
    php-fpm:
      # image: teclaelvis01/php-fpm:7.2.2
      build:
        context: ./php-fpm
        args:
          - INSTALL_XDEBUG=true

      volumes:
        - ./php-fpm/php7.2.ini:/usr/local/etc/php/php.ini
        - ../:/var/www:cached
        - ./xdebug:/var/logs/xdebug
      expose:
        - "9000:9000"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        XDEBUG_MODE: "${XDEBUG_MODE}" 
### NGINX Server #########################################
    nginx:
      image: teclaelvis01/nginx:0.0.1
      container_name: nginx_tork_es
      volumes:
        - ../:/var/www:cached
        - ./logs/nginx:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/ssl/:/etc/nginx/ssl
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm

### MariaDB ##############################################
    mariadb:
      image: teclaelvis01/mariadb:10
      container_name: mariadb_tork_es
      volumes:
        - ./datadb/mariadb:/var/lib/mysql
        - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      environment:
        - TZ=UTC
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
